# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DyadUpdate <- function(Y, C) {
    .Call('_DistCov_DyadUpdate', PACKAGE = 'DistCov', Y, C)
}

add_vector <- function(X, Y) {
    .Call('_DistCov_add_vector', PACKAGE = 'DistCov', X, Y)
}

match_coords <- function(X, Y) {
    .Call('_DistCov_match_coords', PACKAGE = 'DistCov', X, Y)
}

normalize_matrix <- function(M, cmM, mM) {
    .Call('_DistCov_normalize_matrix', PACKAGE = 'DistCov', M, cmM, mM)
}

hadamard_product <- function(X, Y) {
    .Call('_DistCov_hadamard_product', PACKAGE = 'DistCov', X, Y)
}

