# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DyadUpdate <- function(Y, C) {
    .Call('_DistCov_DyadUpdate', PACKAGE = 'DistCov', Y, C)
}

normalize_matrix <- function(M, cmM, mM) {
    .Call('_DistCov_normalize_matrix', PACKAGE = 'DistCov', M, cmM, mM)
}

hadamard_product <- function(X, Y) {
    .Call('_DistCov_hadamard_product', PACKAGE = 'DistCov', X, Y)
}

vector_product <- function(X, Y) {
    .Call('_DistCov_vector_product', PACKAGE = 'DistCov', X, Y)
}

matrix_prod_sum <- function(X, Y) {
    .Call('_DistCov_matrix_prod_sum', PACKAGE = 'DistCov', X, Y)
}

vector_prod_sum <- function(X, Y) {
    .Call('_DistCov_vector_prod_sum', PACKAGE = 'DistCov', X, Y)
}

specific_vector_prod_sum <- function(X, Y, gamma_1, gamma_X, gamma_Y, gamma_XY) {
    .Call('_DistCov_specific_vector_prod_sum', PACKAGE = 'DistCov', X, Y, gamma_1, gamma_X, gamma_Y, gamma_XY)
}

matrix_sum <- function(X) {
    .Call('_DistCov_matrix_sum', PACKAGE = 'DistCov', X)
}

vector_prod_sum_sample <- function(X, Y, s) {
    .Call('_DistCov_vector_prod_sum_sample', PACKAGE = 'DistCov', X, Y, s)
}

